# Generated by Django 5.2.4 on 2025-07-09 10:29

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_content_file_image_text_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=251),
        ),
    ]
