# Generated by Django 5.2.4 on 2025-07-09 10:30

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
